### ISSUE TITLE
Exception loading webapp at http://localhost:8080/greenhouse/

### ISSUE THREAD

**Issue by lrkwz** [spring-projects/greenhouse#6]
``` bash
~/spring-mobile> git clone https://github.com/SpringSource/greenhouse.git

~/spring-mobile> cd greenhouse/

~/s/greenhouse> mvn -version
Apache Maven 3.0.3 (r1075438; 2011-02-28 18:31:09+0100)
Maven home: /opt/apache-maven-3.0.3
Java version: 1.6.0_26, vendor: Sun Microsystems Inc.
Java home: /usr/lib/jvm/java-6-sun-1.6.0.26/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "2.6.38-11-generic", arch: "i386", family: "unix"

~/s/greenhouse> mvn clean install t7:run
(...)
Oct 14, 2011 11:51:08 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [appServlet] in context with path [/greenhouse] threw exception [Handler processing failed; nested exception is java.lang.LinkageError: loader constraint violation: loader (instance of org/apache/catalina/loader/WebappClassLoader) previously initiated loading for a different type with name "javax/el/ExpressionFactory"] with root cause
java.lang.LinkageError: loader constraint violation: loader (instance of org/apache/catalina/loader/WebappClassLoader) previously initiated loading for a different type with name "javax/el/ExpressionFactory"
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2820)
    at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1150)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1645)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1523)
    at org.apache.tiles.el.ELAttributeEvaluator.evaluate(ELAttributeEvaluator.java:151)
```

**Comment by jasmeetsasan2014** [comment]
Getting 404 while Building the project! Any suggestions?

**Comment by jasmeetsasan2014** [comment]
![image](https://cloud.githubusercontent.com/assets/6505336/8603423/99d20cb0-263d-11e5-8480-a952a4e0b109.png)
